# Generated by Django 5.2.16 on 2026-07-23 18:40

import asistente.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('redes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Titulo')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada')], default='activa', max_length=12, verbose_name='Estado')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('negocio_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='negocios.negocio', verbose_name='Negocio activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversacion',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ('-actualizada_el',),
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente'), ('sistema', 'Sistema')], max_length=10, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('modelo_usado', models.CharField(blank=True, max_length=60, verbose_name='Modelo usado')),
                ('tokens_entrada', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('tokens_salida', models.PositiveIntegerField(default=0, verbose_name='Tokens de salida')),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Latencia en milisegundos')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='asistente.conversacion', verbose_name='Conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ('creado_el',),
            },
        ),
        migrations.CreateModel(
            name='AccionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_capacidad', models.CharField(max_length=60, verbose_name='Codigo de capacidad')),
                ('descripcion', models.TextField(verbose_name='Que se va a hacer')),
                ('justificacion', models.TextField(blank=True, verbose_name='Por que se propone')),
                ('advertencia', models.TextField(blank=True, verbose_name='Advertencia')),
                ('carga_util', models.JSONField(blank=True, default=dict, verbose_name='Carga util')),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10, verbose_name='Nivel de riesgo')),
                ('verbo', models.CharField(default='CONFIRMAR', max_length=40, verbose_name='Verbo')),
                ('codigo_confirmacion', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Codigo de confirmacion')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('ejecutada', 'Ejecutada'), ('fallida', 'Fallida')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('vence_el', models.DateTimeField(default=asistente.models.vencimiento_por_defecto, verbose_name='Vence el')),
                ('confirmada_el', models.DateTimeField(blank=True, null=True, verbose_name='Confirmada el')),
                ('ejecutada_el', models.DateTimeField(blank=True, null=True, verbose_name='Ejecutada el')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='negocios.negocio', verbose_name='Negocio')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='redes.redconectada', verbose_name='Red conectada')),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='asistente.conversacion', verbose_name='Conversacion')),
                ('mensaje_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='asistente.mensaje', verbose_name='Mensaje de origen')),
            ],
            options={
                'verbose_name': 'Accion pendiente',
                'verbose_name_plural': 'Acciones pendientes',
                'ordering': ('-creada_el',),
            },
        ),
        migrations.CreateModel(
            name='ReglaPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_capacidad', models.CharField(max_length=60, verbose_name='Codigo de capacidad')),
                ('condicion', models.TextField(verbose_name='Cuando se aplica')),
                ('criterio', models.JSONField(blank=True, default=dict, verbose_name='Criterio')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('veces_aplicada', models.PositiveIntegerField(default=0, verbose_name='Veces aplicada')),
                ('ultima_aplicacion', models.DateTimeField(blank=True, null=True, verbose_name='Ultima aplicacion')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('creada_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas', to='asistente.mensaje', verbose_name='Mensaje de origen')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Regla permanente',
                'verbose_name_plural': 'Reglas permanentes',
                'ordering': ('-creada_el',),
            },
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'creado_el'], name='asistente_m_convers_a68b02_idx'),
        ),
        migrations.AddIndex(
            model_name='accionpendiente',
            index=models.Index(fields=['negocio', 'estado'], name='asistente_a_negocio_d05577_idx'),
        ),
        migrations.AddConstraint(
            model_name='accionpendiente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente'), models.Q(('codigo_confirmacion', ''), _negated=True)), fields=('codigo_confirmacion',), name='codigo_confirmacion_unico_entre_pendientes'),
        ),
    ]
