# Generated by Django 5.2.16 on 2026-07-23 06:46

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('color_primario', models.CharField(default='#000000', max_length=7)),
                ('color_secundario', models.CharField(default='#FFFFFF', max_length=7)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', max_length=60)),
                ('idioma', models.CharField(default='es-ar', max_length=10)),
                ('estado', models.CharField(choices=[('prueba', 'Prueba'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='prueba', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.cuenta')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
