from django.core.management.base import BaseCommand
from capacidades.models import Capacidad


class Command(BaseCommand):
    help = "Carga o actualiza el catalogo de capacidades de las APIs"

    CAPACIDADES = [
        {
            "codigo": "instagram.publicar_imagen",
            "plataforma": "instagram",
            "nombre": "Publicar una imagen",
            "permiso_requerido": "instagram_content_publish",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.publicar_carrusel",
            "plataforma": "instagram",
            "nombre": "Publicar un carrusel",
            "permiso_requerido": "instagram_content_publish",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.publicar_reel",
            "plataforma": "instagram",
            "nombre": "Publicar un reel",
            "permiso_requerido": "instagram_content_publish",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.publicar_historia",
            "plataforma": "instagram",
            "nombre": "Publicar una historia",
            "permiso_requerido": "instagram_content_publish",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.leer_comentarios",
            "plataforma": "instagram",
            "nombre": "Leer comentarios",
            "permiso_requerido": "instagram_manage_comments",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.responder_comentario",
            "plataforma": "instagram",
            "nombre": "Responder un comentario",
            "permiso_requerido": "instagram_manage_comments",
            "tipo": "escritura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.ocultar_comentario",
            "plataforma": "instagram",
            "nombre": "Ocultar o mostrar un comentario",
            "permiso_requerido": "instagram_manage_comments",
            "tipo": "escritura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.borrar_comentario",
            "plataforma": "instagram",
            "nombre": "Borrar un comentario",
            "permiso_requerido": "instagram_manage_comments",
            "tipo": "escritura",
            "riesgo": "alto",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.leer_mensajes",
            "plataforma": "instagram",
            "nombre": "Leer mensajes directos",
            "permiso_requerido": "instagram_manage_messages",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.responder_mensaje",
            "plataforma": "instagram",
            "nombre": "Responder un mensaje directo",
            "permiso_requerido": "instagram_manage_messages",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.respuesta_privada",
            "plataforma": "instagram",
            "nombre": "Responder en privado a un comentario",
            "permiso_requerido": "instagram_manage_messages",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.leer_metricas",
            "plataforma": "instagram",
            "nombre": "Leer metricas de cuenta y publicaciones",
            "permiso_requerido": "instagram_manage_insights",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "metricas",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.buscar_hashtag",
            "plataforma": "instagram",
            "nombre": "Buscar contenido por hashtag",
            "permiso_requerido": "instagram_manage_insights",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "competencia",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.descubrir_negocio",
            "plataforma": "instagram",
            "nombre": "Ver datos publicos de otra cuenta profesional",
            "permiso_requerido": "instagram_manage_insights",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "competencia",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "instagram.editar_publicacion",
            "plataforma": "instagram",
            "nombre": "Editar una publicacion ya publicada",
            "permiso_requerido": "",
            "tipo": "escritura",
            "riesgo": "alto",
            "categoria": "contenido",
            "disponibilidad": "no_existe",
            "notas": "La API no permite editar contenido publicado. Solo se puede borrar y volver a publicar, perdiendo los comentarios.",
        },
        {
            "codigo": "facebook.publicar_pagina",
            "plataforma": "facebook",
            "nombre": "Publicar en una pagina",
            "permiso_requerido": "pages_manage_posts",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "facebook.leer_comentarios",
            "plataforma": "facebook",
            "nombre": "Leer comentarios de la pagina",
            "permiso_requerido": "pages_read_engagement",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "facebook.responder_comentario",
            "plataforma": "facebook",
            "nombre": "Responder un comentario de la pagina",
            "permiso_requerido": "pages_manage_engagement",
            "tipo": "escritura",
            "riesgo": "bajo",
            "categoria": "interacciones",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "facebook.leer_metricas",
            "plataforma": "facebook",
            "nombre": "Leer metricas de la pagina",
            "permiso_requerido": "pages_read_engagement",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "metricas",
            "disponibilidad": "existe",
            "notas": "",
        },
        {
            "codigo": "facebook.publicar_perfil_personal",
            "plataforma": "facebook",
            "nombre": "Publicar en un perfil personal",
            "permiso_requerido": "",
            "tipo": "escritura",
            "riesgo": "medio",
            "categoria": "contenido",
            "disponibilidad": "no_existe",
            "notas": "La API solo permite publicar en paginas, nunca en perfiles personales.",
        },
        {
            "codigo": "tiktok.analizar_competencia",
            "plataforma": "tiktok",
            "nombre": "Analizar perfiles de la competencia",
            "permiso_requerido": "",
            "tipo": "lectura",
            "riesgo": "bajo",
            "categoria": "competencia",
            "disponibilidad": "prohibida",
            "notas": "La Research API esta reservada a investigadores academicos aprobados de Estados Unidos y la Union Europea. No hay via comercial legal.",
        },
    ]

    def handle(self, *args, **options):
        creadas = 0
        actualizadas = 0
        for item in self.CAPACIDADES:
            datos = dict(item)
            codigo = datos.pop("codigo")
            _, created = Capacidad.objects.update_or_create(
                codigo=codigo,
                defaults=datos,
            )
            if created:
                creadas += 1
            else:
                actualizadas += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Capacidades sembradas con exito. Creadas: {creadas}, Actualizadas: {actualizadas}"
            )
        )

