# Generated by Django 5.2.16 on 2026-07-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio mensual')),
                ('moneda', models.CharField(default='ARS', max_length=3, verbose_name='Moneda')),
                ('max_negocios', models.PositiveSmallIntegerField(default=1, verbose_name='Maximo de negocios')),
                ('max_redes_por_negocio', models.PositiveSmallIntegerField(default=2, verbose_name='Maximo de redes por negocio')),
                ('max_publicaciones_mes', models.PositiveIntegerField(default=30, verbose_name='Maximo de publicaciones por mes')),
                ('max_tokens_mes', models.PositiveIntegerField(default=100000, verbose_name='Maximo de tokens de IA por mes')),
                ('max_usuarios', models.PositiveSmallIntegerField(default=1, verbose_name='Maximo de usuarios')),
                ('funcionalidades', models.JSONField(blank=True, default=list, verbose_name='Funcionalidades incluidas')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de presentacion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('orden', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='EventoPagoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='mercadopago', max_length=20, verbose_name='Proveedor')),
                ('tipo', models.CharField(max_length=40, verbose_name='Tipo de evento')),
                ('clave_idempotencia', models.CharField(max_length=160, unique=True, verbose_name='Clave de idempotencia')),
                ('carga_util', models.JSONField(default=dict, verbose_name='Carga util recibida')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('procesado_el', models.DateTimeField(blank=True, null=True, verbose_name='Procesado el')),
                ('recibido_el', models.DateTimeField(auto_now_add=True, verbose_name='Recibido el')),
            ],
            options={
                'verbose_name': 'Evento de pago externo',
                'verbose_name_plural': 'Eventos de pago externos',
                'ordering': ('-recibido_el',),
                'indexes': [models.Index(fields=['procesado', 'recibido_el'], name='facturacion_procesa_bb2a82_idx')],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('prueba', 'En prueba'), ('activa', 'Activa'), ('gracia', 'En gracia'), ('morosa', 'Morosa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='prueba', max_length=12, verbose_name='Estado')),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('fin_prueba', models.DateField(blank=True, null=True, verbose_name='Fin de la prueba')),
                ('proximo_cobro', models.DateField(blank=True, null=True, verbose_name='Proximo cobro')),
                ('id_preaprobacion', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Identificador de preaprobacion')),
                ('cancelada_el', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada el')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='tenants.cuenta', verbose_name='Cuenta')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='facturacion.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ('-creada_el',),
            },
        ),
        migrations.CreateModel(
            name='ConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer dia del mes al que corresponde el consumo', verbose_name='Periodo')),
                ('tokens_entrada', models.PositiveBigIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('tokens_salida', models.PositiveBigIntegerField(default=0, verbose_name='Tokens de salida')),
                ('llamadas', models.PositiveIntegerField(default=0, verbose_name='Llamadas al modelo')),
                ('segundos_computo', models.PositiveIntegerField(default=0, verbose_name='Segundos de computo')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='tenants.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Consumo de IA',
                'verbose_name_plural': 'Consumos de IA',
                'ordering': ('-periodo',),
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'periodo'), name='consumo_unico_por_cuenta_y_periodo')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(default='ARS', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('proveedor', models.CharField(default='mercadopago', max_length=20, verbose_name='Proveedor')),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Identificador externo')),
                ('medio_pago', models.CharField(blank=True, max_length=40, verbose_name='Medio de pago')),
                ('periodo_desde', models.DateField(blank=True, null=True, verbose_name='Periodo desde')),
                ('periodo_hasta', models.DateField(blank=True, null=True, verbose_name='Periodo hasta')),
                ('pagado_el', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.suscripcion', verbose_name='Suscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-creado_el',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('proveedor', 'id_externo'), name='pago_externo_unico')],
            },
        ),
    ]
