# Generated by Django 5.2.16 on 2026-07-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripcion corta')),
                ('modo', models.CharField(choices=[('qr', 'Codigo QR'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('gratis', 'Sin costo')], max_length=20, verbose_name='Modo')),
                ('instrucciones', models.TextField(blank=True, verbose_name='Instrucciones para el cliente')),
                ('requiere_comprobante', models.BooleanField(default=False, verbose_name='Requiere comprobante')),
                ('requiere_aprobacion_manual', models.BooleanField(default=False, verbose_name='Requiere aprobacion manual')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Datos no sensibles. Nunca guardar claves ni tokens aca.', verbose_name='Configuracion')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de presentacion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ('orden', 'codigo'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='medios_pago',
            field=models.ManyToManyField(blank=True, related_name='planes', to='facturacion.mediopago', verbose_name='Medios de pago habilitados'),
        ),
    ]
