# Generated by Django 5.2.16 on 2026-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google_business', 'Google Business Profile'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('bluesky', 'Bluesky'), ('telegram', 'Telegram')], max_length=20, verbose_name='Plataforma')),
                ('codigo', models.CharField(max_length=60, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('permiso_requerido', models.CharField(blank=True, max_length=120, verbose_name='Permiso requerido')),
                ('disponibilidad', models.CharField(choices=[('existe', 'Existe en la API'), ('no_existe', 'No existe en la API'), ('prohibida', 'Prohibida por la plataforma')], default='existe', max_length=15, verbose_name='Disponibilidad')),
                ('estado_revision', models.CharField(choices=[('no_solicitado', 'No solicitado'), ('en_revision', 'En revision'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='no_solicitado', max_length=15, verbose_name='Estado de revision')),
                ('tipo', models.CharField(choices=[('lectura', 'Lectura'), ('escritura', 'Escritura')], default='lectura', max_length=10, verbose_name='Tipo')),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10, verbose_name='Nivel de riesgo')),
                ('categoria', models.CharField(choices=[('metricas', 'Metricas y analisis'), ('interacciones', 'Comentarios y mensajes'), ('contenido', 'Creacion y publicacion'), ('competencia', 'Analisis de competencia'), ('estrategia', 'Estrategia y planificacion'), ('cuenta', 'Administracion de la cuenta')], max_length=20, verbose_name='Categoria de intencion')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Capacidad',
                'verbose_name_plural': 'Capacidades',
                'ordering': ('plataforma', 'codigo'),
                'indexes': [models.Index(fields=['plataforma', 'categoria'], name='capacidades_platafo_a7da3f_idx')],
            },
        ),
    ]
