# Generated by Django 5.2.16 on 2026-07-23 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('estado', models.CharField(choices=[('propuesta', 'Propuesta'), ('aprobada', 'Aprobada'), ('vencida', 'Vencida')], default='propuesta', max_length=15, verbose_name='Estado')),
                ('periodo_desde', models.DateField(verbose_name='Periodo desde')),
                ('periodo_hasta', models.DateField(verbose_name='Periodo hasta')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('metrica_objetivo', models.CharField(blank=True, max_length=60, verbose_name='Metrica objetivo')),
                ('valor_meta', models.CharField(blank=True, max_length=60, verbose_name='Valor meta')),
                ('aprobada_el', models.DateTimeField(blank=True, null=True, verbose_name='Aprobada el')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='estrategia.estrategia', verbose_name='Version anterior')),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='PilarContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('peso', models.PositiveSmallIntegerField(default=25, verbose_name='Peso')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilares', to='estrategia.estrategia', verbose_name='Estrategia')),
            ],
            options={
                'verbose_name': 'Pilar de contenido',
                'verbose_name_plural': 'Pilares de contenido',
                'ordering': ('-peso',),
            },
        ),
        migrations.CreateModel(
            name='RitmoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google_business', 'Google Business Profile'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('bluesky', 'Bluesky'), ('telegram', 'Telegram')], max_length=20, verbose_name='Plataforma')),
                ('formato', models.CharField(choices=[('imagen', 'Imagen'), ('carrusel', 'Carrusel'), ('video', 'Video'), ('reel', 'Reel'), ('historia', 'Historia'), ('texto', 'Texto')], max_length=20, verbose_name='Formato')),
                ('veces_por_semana', models.PositiveSmallIntegerField(default=1, verbose_name='Veces por semana')),
                ('dias_preferidos', models.CharField(blank=True, max_length=60, verbose_name='Dias preferidos')),
                ('franja_horaria', models.CharField(blank=True, max_length=40, verbose_name='Franja horaria')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritmos', to='estrategia.estrategia', verbose_name='Estrategia')),
            ],
            options={
                'verbose_name': 'Ritmo de publicacion',
                'verbose_name_plural': 'Ritmos de publicacion',
                'ordering': ('plataforma', 'formato'),
            },
        ),
        migrations.AddConstraint(
            model_name='estrategia',
            constraint=models.UniqueConstraint(fields=('negocio', 'version'), name='estrategia_version_unica_por_negocio'),
        ),
    ]
