# Generated by Django 5.2.16 on 2026-07-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completitud', models.PositiveSmallIntegerField(default=0, verbose_name='Completitud')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Briefing',
                'verbose_name_plural': 'Briefings',
            },
        ),
        migrations.CreateModel(
            name='HechoBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('oferta', 'Oferta'), ('operacion', 'Operacion'), ('diferencial', 'Diferencial'), ('restriccion', 'Restriccion'), ('activos', 'Activos')], max_length=20, verbose_name='Categoria')),
                ('clave', models.CharField(max_length=100, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('origen', models.CharField(choices=[('dicho', 'Dicho por el usuario'), ('deducido', 'Deducido por la IA')], default='dicho', max_length=10, verbose_name='Origen')),
                ('confianza', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='alta', max_length=10, verbose_name='Confianza')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado por el usuario')),
                ('vigente_desde', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos', to='briefing.briefing', verbose_name='Briefing')),
            ],
            options={
                'verbose_name': 'Hecho del briefing',
                'verbose_name_plural': 'Hechos del briefing',
                'ordering': ('categoria', 'clave'),
                'indexes': [models.Index(fields=['briefing', 'categoria'], name='briefing_he_briefin_a4a11f_idx')],
            },
        ),
    ]
