# Generated by Django 5.2.16 on 2026-07-23 08:12

import core.campos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedConectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google_business', 'Google Business Profile'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('bluesky', 'Bluesky'), ('telegram', 'Telegram')], max_length=20, verbose_name='Plataforma')),
                ('id_externo', models.CharField(max_length=120, verbose_name='Identificador en la red')),
                ('nombre_externo', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la cuenta en la red')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('token_vencido', 'Token vencido'), ('revocada', 'Revocada'), ('error', 'Con error')], default='activa', max_length=20, verbose_name='Estado')),
                ('conectada_el', models.DateTimeField(auto_now_add=True, verbose_name='Conectada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Red conectada',
                'verbose_name_plural': 'Redes conectadas',
                'ordering': ('negocio', 'plataforma'),
            },
        ),
        migrations.CreateModel(
            name='CredencialOAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', core.campos.CampoCifrado(verbose_name='Token de acceso')),
                ('token_refresco', core.campos.CampoCifrado(blank=True, null=True, verbose_name='Token de refresco')),
                ('permisos', models.JSONField(blank=True, default=list, verbose_name='Permisos otorgados')),
                ('vence_el', models.DateTimeField(blank=True, null=True, verbose_name='Vence el')),
                ('ultimo_refresco', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo refresco')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por vencer'), ('vencida', 'Vencida'), ('revocada', 'Revocada')], default='vigente', max_length=15, verbose_name='Estado')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('red', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='redes.redconectada', verbose_name='Red conectada')),
            ],
            options={
                'verbose_name': 'Credencial OAuth',
                'verbose_name_plural': 'Credenciales OAuth',
            },
        ),
        migrations.AddIndex(
            model_name='redconectada',
            index=models.Index(fields=['negocio', 'plataforma'], name='redes_redco_negocio_0526d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='redconectada',
            constraint=models.UniqueConstraint(fields=('negocio', 'plataforma', 'id_externo'), name='red_unica_por_negocio'),
        ),
    ]
