# Generated by Django 5.2.16 on 2026-07-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actor', models.CharField(choices=[('usuario', 'Usuario'), ('ia', 'IA'), ('sistema', 'Sistema')], default='usuario', max_length=10, verbose_name='Tipo de actor')),
                ('accion', models.CharField(max_length=80, verbose_name='Accion')),
                ('objeto_tipo', models.CharField(blank=True, max_length=60, verbose_name='Tipo de objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=60, verbose_name='Identificador del objeto')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='Detalle')),
                ('resultado', models.CharField(choices=[('exito', 'Exito'), ('error', 'Error')], default='exito', max_length=10, verbose_name='Resultado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Evento de bitacora',
                'verbose_name_plural': 'Eventos de bitacora',
                'ordering': ('-creado_el',),
                'indexes': [models.Index(fields=['negocio', 'creado_el'], name='bitacora_ev_negocio_4b1757_idx'), models.Index(fields=['accion'], name='bitacora_ev_accion_ea16e8_idx')],
            },
        ),
    ]
